defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-25-alpha

version: 2
jobs:
  prepare_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Decipher keystore.properties
          command: openssl enc -d -aes256 -base64 -in app/keystore.properties.enc -out app/keystore.properties -k $KEYSTORE_KEY -md md5
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  run_code_analyzers:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Lint Report
          command: ./gradlew lint
      - run:
          name: Build PMD Report
          command: ./gradlew pmd
      - run:
          name: Build Checkstyle Report
          command: ./gradlew checkstyle
      - store_artifacts:
          path: app/build/outputs/checkstyle
          destination: reports
      - store_artifacts:
          path: app/build/outputs/pmd
          destination: reports
      - store_artifacts:
          path: app/build/outputs/findbugs
          destination: reports
      - store_artifacts:
          path: app/build/reports/
          destination: reports
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  build_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy APK.
          command: |
              bash ./scripts/deploy-hockey.sh
              bash ./scripts/deploy-fabric.sh

workflows:
  version: 2
  build:
    jobs:
      - prepare_dependencies
      - run_code_analyzers:
          requires:
            - prepare_dependencies
      - run_tests:
          requires:
            - run_code_analyzers
      - build_app:
          requires:
            - run_tests
      - deploy_release:
          requires:
            - build_app
          filters:
            branches:
              only: master
